### PR TITLE
Added script for building both native as java libs.

### LINKED ISSUE #2: Cant download gdx-video-desktop-natives.jar
Hello, i tried the maven build but i can't download the gdx-video-desktop-natives.jar
I can't find it in any of my repos including the one mentioned in read.me

Could you help?

### PR DESCRIPTION
**Pull request by RBogie**
This PR enables the building of both the ffmpeg natives, as the java project on the TravisCI servers. If this is expanded to release to maven repos, it will function as a full buildserver. This would fix #2.

@Tom-Ski Could you add the deploy to maven repos if/when you have time?

### CODE REVIEW

**Comment by intrigus** [comment]
Hi, what exactly is missing for merge?
Is only deploying to maven repos missing?

**Comment by Robbiedobbie** [comment]
Indeed the deploying still has to be done. However, I don't have any authentication info for maven central. Someone who does have the information needed should add it through encrypted variables in travis.

**Comment by SimonIT** [comment]
Even if deploying is still missing, I think the building itself is a good addition so I'm merging it

**Comment by SimonIT** [comment]
@Tom-Ski Can you enable travis for this repo?

**Comment by Tom-Ski** [comment]
Don, triggered first build for that branch

**Comment by SimonIT** [comment]
Thank you

**Pull request merged**
